name: CI

on:
  push:
    branches:
      - feature/**

  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        ports:
          - 3306:3306
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: mysql
          MYSQL_ROOT_PASSWORD: mysql
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build -c Release
      - name: Unit Test
        run: dotnet test -c Release --no-build --filter Category!=Integration
      - name: Integration Test
        run: dotnet test -c Release --no-build --filter Category=Integration